source 'https://rubygems.org'

gem 'teacup'
gem 'sugarcube'
gem 'sweettea', :git => 'https://github.com/colinta/sweettea'
gem 'bubble-wrap'
gem 'geomotion'
gem 'ProMotion', '1.0.3'
gem 'motion-cocoapods'
gem 'formotion', '1.5.1'
gem 'motion-testflight'
