# This file is automatically generated. Do not edit.

if Object.const_defined?('TestFlight') and !UIDevice.currentDevice.model.include?('Simulator')
  NSNotificationCenter.defaultCenter.addObserverForName(UIApplicationDidBecomeActiveNotification, object:nil, queue:nil, usingBlock:lambda do |notification|
  
  TestFlight.takeOff('3d16e5ffd0bb2878102deabf5a68bd28_ODk5NjYyMDEyLTA1LTE0IDA0OjIxOjA0LjI4OTM4Ng')
  end)
end
